import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lato, Geist, Geist_Mono, Poppins, Syne, Inter, DM_Sans, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

const clashGrotesk = localFont({
  src: "../public/fonts/ClashGrotesk-Semibold.otf",
  variable: "--font-clash-grotesk",
  display: "swap",
});

const clashGroteskreg = localFont({
  src: "../public/fonts/ClashGrotesk-Regular.otf",
  variable: "--font-clash-grotesk-reg",
  display: "swap",
});
const clashGroteskmedium = localFont({
  src: "../public/fonts/ClashGrotesk-Medium.otf",
  variable: "--font-clash-grotesk-medium",
  display: "swap",
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geist.variable} ${geistMono.variable} ${syne.variable} ${lato.variable} ${inter.variable} ${dmSans.variable} ${poppins.variable} ${plusJakartaSans.variable} ${clashGrotesk.variable} ${clashGroteskreg.variable} ${clashGroteskmedium.variable} h-full antialiased`}
    >
      <body className={plusJakartaSans.className}>{children}</body>
    </html>
  );
}
